name: mkdocs
on:
  push:
    branches:
      - mkdocs
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENABLE_STRICT: true
      ENABLE_MINIFY: true
      ENABLE_REMOVE_COMMENTS: true
      ENABLE_GIT_AUTHORS: false
      ENABLE_GIT_COMMITTERS: false
      ENABLE_GIT_REVISION_DATE: false
      ENABLE_STRICT_GIT_AUTHORS: false
      ENABLE_STRICT_GIT_REVISION_DATE: true
      ENABLE_OFFLINE: true
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - run: uv sync
      - run: uv run mkdocs build